export const MATERNITY_STATUSES = [
  'DRAFT',
  'SUBMITTED_TO_ZAGS',
  'REGISTERED_BY_ZAGS',
  'REJECTED',
  'ARCHIVED',
] as const;

export const MATERNITY_GENDERS = ['MALE', 'FEMALE', 'UNKNOWN'] as const;

export const MATERNITY_BIRTH_CASE_TYPES = [
  'STANDARD_MARRIAGE',
  'OUT_OF_WEDLOCK',
  'UNREGISTERED_MARRIAGE',
  'RELATIVE_WITHOUT_ZAGS',
  'GUARDIANSHIP',
] as const;
